name: Update Index Value

on:
  schedule:
    - cron: '5 * * * *'

permissions:
  contents: write

jobs:
  update:
    name: Update MSIndex
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - name: Run zig update
        env:
          FRED_KEY: ${{ secrets.FRED_KEY }}
        run: zig build run-update
      - name: Commit report
        run: |
          git diff 
      - name: Commit report
        run: |
          git pull
          git config --global user.name 'Connor Rowland'
          git config --global user.email 'connor.k.rowland@icloud.com'
          git commit -am "Update JSON files"
          git push
