name: Update Index Value

on: [push]
#  schedule:
#    - cron: '0 1 * * 1-5' # every workday at 6pm PST

permissions:
  contents: write

jobs:
  update:
    name: Update MSIndex
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - name: Run zig update
        env:
          FRED_KEY: ${{ secrets.FRED_KEY }}
        run: zig build run-update
      - name: Commit to main
        run: |
          git pull
          git config --global user.name 'Connor Rowland'
          git config --global user.email 'connor.k.rowland@icloud.com'
          git add *
          git commit -m "Update JSON files"
          git push
      - name: Check out pages branch 
        uses: actions/checkout@v4
        with:
          ref: pages
      - name: Commit to pages
        run: |
          git fetch origin main
          git checkout origin/main --no-overlay -- static/json
          rm -rf json
          mv static/json json
          rm -rf static
          git add *
          git commit -m "Update JSON files"
          git push
